# Generated by Django 5.2.2 on 2025-06-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_menu',
            field=models.BooleanField(default=True),
        ),
    ]
